version: "1.0"
registry:
  uri: "silkit://localhost:8500"

participants:
  - name: "AC_Panel"
    can:
      controllers:
        - name: "CAN1"
          network: "VehicleCAN"
          baudrate: 500000
          
  - name: "AC_Control"
    can:
      controllers:
        - name: "CAN1"
          network: "VehicleCAN"
          baudrate: 500000
          
  - name: "Thermal_Model"
    can:
      controllers:
        - name: "CAN1"
          network: "VehicleCAN"
          baudrate: 500000

networks:
  - name: "VehicleCAN"
    type: "CAN"
    spec:
      baudrate: 500000 